In [ ]:
!pip install duckdb pandas

Requirement already satisfied: duckdb in /usr/local/lib/python3.12/dist-packages (1.3.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import duckdb
import pandas as pd

In [ ]:
con = duckdb.connect()

In [ ]:
con.execute("SELECT 1").fetchall()

[(1,)]

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving r3_ed_opendata.csv to r3_ed_opendata.csv

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving r3_primarycare_opendata.csv to r3_primarycare_opendata.csv

In [ ]:
import os
os.listdir()

['.config', 'r3_primarycare_opendata.csv', 'r3_ed_opendata.csv', 'sample_data']

In [ ]:
ed = pd.read_csv("r3_ed_opendata.csv")
primary = pd.read_csv("r3_primarycare_opendata.csv")

In [ ]:
ed.shape

(4370, 22)

In [ ]:
primary.shape

(4366, 13)

In [ ]:
ed.columns

Index(['Geo_FIPS', 'StateFIPS', 'CountyFIPS', 'TractFIPS', 'BlockgroupFIPS',
       'TotalPopEst2015_19ACS', 'YearOfStartDate', 'UnderAge1PopEst2015_19ACS',
       'Age0to17PopEst2015_19ACS', 'Unique0to17WithED_Visit',
       'Unique0to17WithED_VisitPer100', 'NumberED_VisitsAge0to17',
       'ED_VisitsPer100Age0to17', 'NumberLowAcuityED_VisitsAge0to17',
       'LowAcuityED_VisitsPer100Age0to17', 'NumberAsthmaRelatedED_Visits',
       'AsthmaRelatedED_VisitsPer100Age0to17',
       'NumberED_VisitsByChildrenUnder1YearOld', 'NumberOfInjuryRelatedVisits',
       'InjuryRelatedEDVisitsPer100Age0to17',
       'NumberAcuteRespiratoryTractInfectionRelatedED_VisitsAge0to17',
       'AcuteRespiratoryTractInfectionRelatedED_VisitsPer100Age0to17'],
      dtype='object')

In [ ]:
primary.columns

Index(['Geo_FIPS', 'StateFIPS', 'CountyFIPS', 'TractFIPS', 'BlockgroupFIPS',
       'TotalPopEst2015_19ACS', 'Age0to17PopEst2015_19ACS',
       'YearOfContactDate', 'AllPrimaryCarePatientsAge0to17',
       'WellChildVisitsInPastYearAge0to17',
       'WellChildVisitsInPastYearPer100PrimaryCarePatients',
       'AsthmaDiagnosisAge0to17',
       'AsthmaDiagnosisPer100PrimaryCarePatientsAge0to17'],
      dtype='object')

In [ ]:
ed = ed.rename(columns={
    "YearOfStartDate": "year"
})

primary = primary.rename(columns={
    "YearOfContactDate": "year"
})

In [ ]:
ed.columns

Index(['Geo_FIPS', 'StateFIPS', 'CountyFIPS', 'TractFIPS', 'BlockgroupFIPS',
       'TotalPopEst2015_19ACS', 'year', 'UnderAge1PopEst2015_19ACS',
       'Age0to17PopEst2015_19ACS', 'Unique0to17WithED_Visit',
       'Unique0to17WithED_VisitPer100', 'NumberED_VisitsAge0to17',
       'ED_VisitsPer100Age0to17', 'NumberLowAcuityED_VisitsAge0to17',
       'LowAcuityED_VisitsPer100Age0to17', 'NumberAsthmaRelatedED_Visits',
       'AsthmaRelatedED_VisitsPer100Age0to17',
       'NumberED_VisitsByChildrenUnder1YearOld', 'NumberOfInjuryRelatedVisits',
       'InjuryRelatedEDVisitsPer100Age0to17',
       'NumberAcuteRespiratoryTractInfectionRelatedED_VisitsAge0to17',
       'AcuteRespiratoryTractInfectionRelatedED_VisitsPer100Age0to17'],
      dtype='object')

In [ ]:
ed["Geo_FIPS"] = ed["Geo_FIPS"].astype(str)
primary["Geo_FIPS"] = primary["Geo_FIPS"].astype(str)

In [ ]:
ed["Geo_FIPS"].dtype

dtype('O')

In [ ]:
ed[["Geo_FIPS","year"]].head()

       Geo_FIPS    year
0  420031301002  2016.0
1  420031301002  2017.0
2  420031301002  2018.0
3  420031301002  2019.0
4  420031301003  2016.0

In [ ]:
primary[["Geo_FIPS","year"]].head()

       Geo_FIPS  year
0  420031301002  2016
1  420031301002  2017
2  420031301002  2018
3  420031301002  2019
4  420031301003  2016

In [ ]:
ed["year"] = ed["year"].astype(int)
primary["year"] = primary["year"].astype(int)

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [ ]:
ed[ed["year"].isna()]

,Geo_FIPS,StateFIPS,CountyFIPS,TractFIPS,BlockgroupFIPS,TotalPopEst2015_19ACS,year,UnderAge1PopEst2015_19ACS,Age0to17PopEst2015_19ACS,Unique0to17WithED_Visit,...,ED_VisitsPer100Age0to17,NumberLowAcuityED_VisitsAge0to17,LowAcuityED_VisitsPer100Age0to17,NumberAsthmaRelatedED_Visits,AsthmaRelatedED_VisitsPer100Age0to17,NumberED_VisitsByChildrenUnder1YearOld,NumberOfInjuryRelatedVisits,InjuryRelatedEDVisitsPer100Age0to17,NumberAcuteRespiratoryTractInfectionRelatedED_VisitsAge0to17,AcuteRespiratoryTractInfectionRelatedED_VisitsPer100Age0to17
4335,420039800001,42,3,980000,1,0,NaN,0.0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4352,420039806001,42,3,980600,1,13,NaN,0.0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4353,420039807001,42,3,980700,1,0,NaN,0.0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4354,420039808001,42,3,980800,1,0,NaN,0.0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4355,420039809001,42,3,980900,1,1313,NaN,0.0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4360,420039811001,42,3,981100,1,0,NaN,0.0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
ed["year"].isna().sum()

np.int64(6)

In [ ]:
ed = ed.dropna(subset=["year"])
primary = primary.dropna(subset=["year"])

In [ ]:
ed["year"] = ed["year"].astype(int)
primary["year"] = primary["year"].astype(int)

In [ ]:
ed["year"].dtype

dtype('int64')

In [ ]:
ed[["Geo_FIPS","year"]].head()

       Geo_FIPS  year
0  420031301002  2016
1  420031301002  2017
2  420031301002  2018
3  420031301002  2019
4  420031301003  2016

In [ ]:
con.register("ed_visits", ed)
con.register("primary_care", primary)

In [ ]:
con.execute("SHOW TABLES").fetchdf()

           name
0     ed_visits
1  primary_care

In [ ]:
con.execute("""
SELECT Geo_FIPS, year
FROM ed_visits
LIMIT 5
""").fetchdf()

       Geo_FIPS  year
0  420031301002  2016
1  420031301002  2017
2  420031301002  2018
3  420031301002  2019
4  420031301003  2016

In [ ]:
con.execute("""
SELECT Geo_FIPS, year
FROM primary_care
LIMIT 5
""").fetchdf()

       Geo_FIPS  year
0  420031301002  2016
1  420031301002  2017
2  420031301002  2018
3  420031301002  2019
4  420031301003  2016

In [ ]:
healthcare_df = con.execute("""
SELECT
    ed.Geo_FIPS,
    ed.year,

    ed.Age0to17PopEst2015_19ACS AS pediatric_population,

    ed.NumberED_VisitsAge0to17,
    ed.NumberLowAcuityED_VisitsAge0to17,
    ed.NumberAsthmaRelatedED_Visits,
    ed.NumberOfInjuryRelatedVisits,
    ed.NumberAcuteRespiratoryTractInfectionRelatedED_VisitsAge0to17,

    primary.AllPrimaryCarePatientsAge0to17,
    primary.WellChildVisitsInPastYearAge0to17,
    primary.AsthmaDiagnosisAge0to17

FROM ed_visits ed
LEFT JOIN primary_care primary
ON ed.Geo_FIPS = primary.Geo_FIPS
AND ed.year = primary.year
""").fetchdf()

ParserException: Parser Error: syntax error at or near "primary"

In [ ]:
ed.columns

Index(['Geo_FIPS', 'StateFIPS', 'CountyFIPS', 'TractFIPS', 'BlockgroupFIPS',
       'TotalPopEst2015_19ACS', 'year', 'UnderAge1PopEst2015_19ACS',
       'Age0to17PopEst2015_19ACS', 'Unique0to17WithED_Visit',
       'Unique0to17WithED_VisitPer100', 'NumberED_VisitsAge0to17',
       'ED_VisitsPer100Age0to17', 'NumberLowAcuityED_VisitsAge0to17',
       'LowAcuityED_VisitsPer100Age0to17', 'NumberAsthmaRelatedED_Visits',
       'AsthmaRelatedED_VisitsPer100Age0to17',
       'NumberED_VisitsByChildrenUnder1YearOld', 'NumberOfInjuryRelatedVisits',
       'InjuryRelatedEDVisitsPer100Age0to17',
       'NumberAcuteRespiratoryTractInfectionRelatedED_VisitsAge0to17',
       'AcuteRespiratoryTractInfectionRelatedED_VisitsPer100Age0to17'],
      dtype='object')

In [ ]:
primary.columns

Index(['Geo_FIPS', 'StateFIPS', 'CountyFIPS', 'TractFIPS', 'BlockgroupFIPS',
       'TotalPopEst2015_19ACS', 'Age0to17PopEst2015_19ACS', 'year',
       'AllPrimaryCarePatientsAge0to17', 'WellChildVisitsInPastYearAge0to17',
       'WellChildVisitsInPastYearPer100PrimaryCarePatients',
       'AsthmaDiagnosisAge0to17',
       'AsthmaDiagnosisPer100PrimaryCarePatientsAge0to17'],
      dtype='object')

In [ ]:
healthcare_df = con.execute("""
SELECT
    ed.Geo_FIPS,
    ed.year,

    ed.Age0to17PopEst2015_19ACS AS pediatric_population,

    ed.NumberED_VisitsAge0to17,
    ed.NumberLowAcuityED_VisitsAge0to17,
    ed.NumberAsthmaRelatedED_Visits,
    ed.NumberOfInjuryRelatedVisits,
    ed.NumberAcuteRespiratoryTractInfectionRelatedED_VisitsAge0to17,

    pc.AllPrimaryCarePatientsAge0to17,
    pc.WellChildVisitsInPastYearAge0to17,
    pc.AsthmaDiagnosisAge0to17

FROM ed_visits ed
LEFT JOIN primary_care pc
ON ed.Geo_FIPS = pc.Geo_FIPS
AND ed.year = pc.year
""").fetchdf()

In [ ]:
healthcare_df.head()

,Geo_FIPS,year,pediatric_population,NumberED_VisitsAge0to17,NumberLowAcuityED_VisitsAge0to17,NumberAsthmaRelatedED_Visits,NumberOfInjuryRelatedVisits,NumberAcuteRespiratoryTractInfectionRelatedED_VisitsAge0to17,AllPrimaryCarePatientsAge0to17,WellChildVisitsInPastYearAge0to17,AsthmaDiagnosisAge0to17
0,420031301002,2016,207,122.0,62.0,40.0,1.0,18.0,82,59,17.0
1,420031301002,2017,207,130.0,80.0,54.0,1.0,27.0,94,58,19.0
2,420031301002,2018,207,138.0,85.0,59.0,2.0,19.0,89,63,19.0
3,420031301002,2019,207,148.0,96.0,68.0,NaN,27.0,86,61,17.0
4,420031301003,2016,134,71.0,39.0,13.0,2.0,10.0,53,34,18.0

In [ ]:
healthcare_df.shape

(4364, 11)

In [ ]:
healthcare_df["ed_visit_rate_per_1000"] = (
    healthcare_df["NumberED_VisitsAge0to17"] * 1000
    / healthcare_df["pediatric_population"]
)

In [ ]:
healthcare_df["asthma_ed_rate"] = (
    healthcare_df["NumberAsthmaRelatedED_Visits"] * 1000
    / healthcare_df["pediatric_population"]
)

In [ ]:
healthcare_df["injury_rate"] = (
    healthcare_df["NumberOfInjuryRelatedVisits"] * 1000
    / healthcare_df["pediatric_population"]
)

In [ ]:
healthcare_df["low_acuity_ratio"] = (
    healthcare_df["NumberLowAcuityED_VisitsAge0to17"]
    / healthcare_df["NumberED_VisitsAge0to17"]
)

In [ ]:
healthcare_df["primary_care_utilization"] = (
    healthcare_df["AllPrimaryCarePatientsAge0to17"]
    / healthcare_df["pediatric_population"]
)

In [ ]:
healthcare_df.columns

Index(['Geo_FIPS', 'year', 'pediatric_population', 'NumberED_VisitsAge0to17',
       'NumberLowAcuityED_VisitsAge0to17', 'NumberAsthmaRelatedED_Visits',
       'NumberOfInjuryRelatedVisits',
       'NumberAcuteRespiratoryTractInfectionRelatedED_VisitsAge0to17',
       'AllPrimaryCarePatientsAge0to17', 'WellChildVisitsInPastYearAge0to17',
       'AsthmaDiagnosisAge0to17', 'ed_visit_rate_per_1000', 'asthma_ed_rate',
       'injury_rate', 'low_acuity_ratio', 'primary_care_utilization'],
      dtype='object')

In [ ]:
healthcare_df.head()

,Geo_FIPS,year,pediatric_population,NumberED_VisitsAge0to17,NumberLowAcuityED_VisitsAge0to17,NumberAsthmaRelatedED_Visits,NumberOfInjuryRelatedVisits,NumberAcuteRespiratoryTractInfectionRelatedED_VisitsAge0to17,AllPrimaryCarePatientsAge0to17,WellChildVisitsInPastYearAge0to17,AsthmaDiagnosisAge0to17,ed_visit_rate_per_1000,asthma_ed_rate,injury_rate,low_acuity_ratio,primary_care_utilization
0,420031301002,2016,207,122.0,62.0,40.0,1.0,18.0,82,59,17.0,589.371981,193.236715,4.830918,0.508197,0.396135
1,420031301002,2017,207,130.0,80.0,54.0,1.0,27.0,94,58,19.0,628.019324,260.869565,4.830918,0.615385,0.454106
2,420031301002,2018,207,138.0,85.0,59.0,2.0,19.0,89,63,19.0,666.666667,285.024155,9.661836,0.615942,0.429952
3,420031301002,2019,207,148.0,96.0,68.0,NaN,27.0,86,61,17.0,714.975845,328.502415,NaN,0.648649,0.415459
4,420031301003,2016,134,71.0,39.0,13.0,2.0,10.0,53,34,18.0,529.850746,97.014925,14.925373,0.549296,0.395522

In [ ]:
healthcare_df.sort_values(
    "ed_visit_rate_per_1000",
    ascending=False
).tail(100)

,Geo_FIPS,year,pediatric_population,NumberED_VisitsAge0to17,NumberLowAcuityED_VisitsAge0to17,NumberAsthmaRelatedED_Visits,NumberOfInjuryRelatedVisits,NumberAcuteRespiratoryTractInfectionRelatedED_VisitsAge0to17,AllPrimaryCarePatientsAge0to17,WellChildVisitsInPastYearAge0to17,AsthmaDiagnosisAge0to17,ed_visit_rate_per_1000,asthma_ed_rate,injury_rate,low_acuity_ratio,primary_care_utilization
88,420031404001,2016,165,12.0,5.0,1.0,NaN,2.0,104,89,10.0,72.727273,6.060606,NaN,0.416667,0.630303
2106,420034560031,2016,358,26.0,9.0,2.0,NaN,4.0,89,73,13.0,72.625698,5.586592,NaN,0.346154,0.248603
2138,420034572002,2016,194,14.0,2.0,NaN,NaN,1.0,19,15,2.0,72.164948,NaN,NaN,0.142857,0.097938
3158,420034911012,2016,1105,79.0,32.0,9.0,2.0,9.0,486,417,60.0,71.493213,8.144796,1.809955,0.405063,0.439819
2656,420034753012,2018,140,10.0,4.0,NaN,1.0,3.0,54,44,10.0,71.428571,NaN,7.142857,0.400000,0.385714
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1784,42003103002,2018,33,1.0,NaN,NaN,NaN,NaN,<NA>,<NA>,NaN,30.303030,NaN,NaN,NaN,<NA>
1783,42003103002,2017,33,1.0,NaN,NaN,NaN,1.0,<NA>,<NA>,NaN,30.303030,NaN,NaN,NaN,<NA>
1785,42003103002,2019,33,1.0,1.0,NaN,NaN,NaN,<NA>,<NA>,NaN,30.303030,NaN,NaN,1.000000,<NA>
1930,42003703002,2017,43,1.0,1.0,NaN,NaN,NaN,<NA>,<NA>,NaN,23.255814,NaN,NaN,1.000000,<NA>
1855,42003406001,2018,43,1.0,NaN,NaN,NaN,NaN,<NA>,<NA>,NaN,23.255814,NaN,NaN,NaN,<NA>

In [ ]:
healthcare_df["pediatric_population"].describe()

count    4364.000000
mean      210.461962
std       176.030524
min         0.000000
25%        96.000000
50%       168.000000
75%       271.000000
max      1755.000000
Name: pediatric_population, dtype: float64

In [ ]:
(healthcare_df["pediatric_population"] == 0).sum()

np.int64(79)

In [ ]:
healthcare_df = healthcare_df[
    healthcare_df["pediatric_population"] > 0
]

In [ ]:
import numpy as np

healthcare_df.replace([np.inf, -np.inf], np.nan, inplace=True)

In [ ]:
healthcare_df = healthcare_df.dropna()

In [ ]:
healthcare_df.describe()

,year,pediatric_population,NumberED_VisitsAge0to17,NumberLowAcuityED_VisitsAge0to17,NumberAsthmaRelatedED_Visits,NumberOfInjuryRelatedVisits,NumberAcuteRespiratoryTractInfectionRelatedED_VisitsAge0to17,AllPrimaryCarePatientsAge0to17,WellChildVisitsInPastYearAge0to17,AsthmaDiagnosisAge0to17,ed_visit_rate_per_1000,asthma_ed_rate,injury_rate,low_acuity_ratio,primary_care_utilization
count,1832.000000,1832.000000,1832.000000,1832.000000,1832.000000,1832.000000,1832.000000,1832.0,1832.0,1832.000000,1832.000000,1832.000000,1832.000000,1832.000000,1832.0
mean,2017.516376,257.370633,84.169214,34.834061,16.718341,1.671397,12.652293,130.108079,107.581878,20.534389,526.369965,114.146040,11.529492,0.406628,0.655017
std,1.114795,202.058985,59.631160,31.792074,17.521286,1.014419,12.436831,100.993694,88.470102,15.407443,660.075535,201.928154,15.895155,0.143000,0.552863
min,2016.000000,8.000000,7.000000,1.000000,1.000000,1.000000,1.000000,10.0,7.0,1.000000,49.411765,1.712329,0.569801,0.051020,0.08
25%,2017.000000,123.000000,46.000000,16.000000,5.000000,1.000000,5.000000,70.75,56.0,11.000000,193.906650,22.407198,4.016064,0.297872,0.371164
50%,2018.000000,212.000000,70.000000,26.000000,12.000000,1.000000,9.000000,104.0,85.0,17.000000,319.801274,51.597363,7.194245,0.406351,0.525754
75%,2019.000000,337.000000,103.250000,43.000000,21.000000,2.000000,16.000000,153.0,125.25,25.000000,603.500841,128.615507,12.422360,0.510230,0.735632
max,2019.000000,1755.000000,613.000000,395.000000,187.000000,9.000000,127.000000,1060.0,924.0,149.000000,7384.615385,3277.777778,187.500000,0.826990,6.375

In [ ]:
healthcare_df.sort_values(
    "ed_visit_rate_per_1000",
    ascending=False
).head()

,Geo_FIPS,year,pediatric_population,NumberED_VisitsAge0to17,NumberLowAcuityED_VisitsAge0to17,NumberAsthmaRelatedED_Visits,NumberOfInjuryRelatedVisits,NumberAcuteRespiratoryTractInfectionRelatedED_VisitsAge0to17,AllPrimaryCarePatientsAge0to17,WellChildVisitsInPastYearAge0to17,AsthmaDiagnosisAge0to17,ed_visit_rate_per_1000,asthma_ed_rate,injury_rate,low_acuity_ratio,primary_care_utilization
4123,420035625002,2018,13,96.0,59.0,24.0,1.0,23.0,72,64,14.0,7384.615385,1846.153846,76.923077,0.614583,5.538462
3978,420035606002,2016,18,132.0,59.0,59.0,1.0,23.0,67,49,15.0,7333.333333,3277.777778,55.555556,0.446970,3.722222
4086,420035623004,2017,11,74.0,35.0,12.0,1.0,8.0,56,46,12.0,6727.272727,1090.909091,90.909091,0.472973,5.090909
4124,420035625002,2019,13,86.0,53.0,16.0,1.0,18.0,70,56,13.0,6615.384615,1230.769231,76.923077,0.616279,5.384615
3980,420035606002,2018,18,114.0,66.0,41.0,2.0,11.0,74,54,13.0,6333.333333,2277.777778,111.111111,0.578947,4.111111

In [ ]:
healthcare_df["pediatric_population"].describe()

count    1832.000000
mean      257.370633
std       202.058985
min         8.000000
25%       123.000000
50%       212.000000
75%       337.000000
max      1755.000000
Name: pediatric_population, dtype: float64

In [ ]:
healthcare_df = healthcare_df[
    healthcare_df["pediatric_population"] >=  0
]

In [ ]:
healthcare_df["pediatric_population"].describe()

count    1521.000000
mean      297.203813
std       199.293157
min       100.000000
25%       163.000000
50%       241.000000
75%       368.000000
max      1755.000000
Name: pediatric_population, dtype: float64

In [ ]:
healthcare_df.sort_values(
    "ed_visit_rate_per_1000",
    ascending=False
).head()

,Geo_FIPS,year,pediatric_population,NumberED_VisitsAge0to17,NumberLowAcuityED_VisitsAge0to17,NumberAsthmaRelatedED_Visits,NumberOfInjuryRelatedVisits,NumberAcuteRespiratoryTractInfectionRelatedED_VisitsAge0to17,AllPrimaryCarePatientsAge0to17,WellChildVisitsInPastYearAge0to17,AsthmaDiagnosisAge0to17,ed_visit_rate_per_1000,asthma_ed_rate,injury_rate,low_acuity_ratio,primary_care_utilization
3887,420035512003,2017,102,230.0,30.0,45.0,1.0,39.0,149,111,26.0,2254.901961,441.176471,9.803922,0.130435,1.460784
3886,420035512003,2016,102,214.0,40.0,57.0,2.0,41.0,161,106,29.0,2098.039216,558.823529,19.607843,0.186916,1.578431
3888,420035512003,2018,102,204.0,29.0,48.0,2.0,29.0,151,103,26.0,2000.000000,470.588235,19.607843,0.142157,1.480392
3627,420035231001,2017,102,188.0,95.0,44.0,2.0,34.0,139,99,24.0,1843.137255,431.372549,19.607843,0.505319,1.362745
3628,420035231001,2018,102,170.0,90.0,42.0,2.0,39.0,151,104,25.0,1666.666667,411.764706,19.607843,0.529412,1.480392

In [ ]:
healthcare_df.sort_values(
    "ed_visit_rate_per_1000",
    ascending=False
).head(10)

,Geo_FIPS,year,pediatric_population,NumberED_VisitsAge0to17,NumberLowAcuityED_VisitsAge0to17,NumberAsthmaRelatedED_Visits,NumberOfInjuryRelatedVisits,NumberAcuteRespiratoryTractInfectionRelatedED_VisitsAge0to17,AllPrimaryCarePatientsAge0to17,WellChildVisitsInPastYearAge0to17,AsthmaDiagnosisAge0to17,ed_visit_rate_per_1000,asthma_ed_rate,injury_rate,low_acuity_ratio,primary_care_utilization
3887,420035512003,2017,102,230.0,30.0,45.0,1.0,39.0,149,111,26.0,2254.901961,441.176471,9.803922,0.130435,1.460784
3886,420035512003,2016,102,214.0,40.0,57.0,2.0,41.0,161,106,29.0,2098.039216,558.823529,19.607843,0.186916,1.578431
3888,420035512003,2018,102,204.0,29.0,48.0,2.0,29.0,151,103,26.0,2000.000000,470.588235,19.607843,0.142157,1.480392
3627,420035231001,2017,102,188.0,95.0,44.0,2.0,34.0,139,99,24.0,1843.137255,431.372549,19.607843,0.505319,1.362745
3628,420035231001,2018,102,170.0,90.0,42.0,2.0,39.0,151,104,25.0,1666.666667,411.764706,19.607843,0.529412,1.480392
3629,420035231001,2019,102,166.0,97.0,26.0,5.0,30.0,145,102,21.0,1627.450980,254.901961,49.019608,0.584337,1.421569
50,420031306003,2018,398,613.0,363.0,187.0,5.0,103.0,347,235,58.0,1540.201005,469.849246,12.562814,0.592170,0.871859
840,420033001005,2016,115,177.0,84.0,62.0,2.0,29.0,97,61,30.0,1539.130435,539.130435,17.391304,0.474576,0.843478
51,420031306003,2019,398,609.0,395.0,148.0,6.0,127.0,341,256,59.0,1530.150754,371.859296,15.075377,0.648604,0.856784
841,420033001005,2017,115,174.0,64.0,59.0,2.0,32.0,107,73,33.0,1513.043478,513.043478,17.391304,0.367816,0.930435

In [ ]:
healthcare_df.sort_values(
    "asthma_ed_rate",
    ascending=False
).head(10)

,Geo_FIPS,year,pediatric_population,NumberED_VisitsAge0to17,NumberLowAcuityED_VisitsAge0to17,NumberAsthmaRelatedED_Visits,NumberOfInjuryRelatedVisits,NumberAcuteRespiratoryTractInfectionRelatedED_VisitsAge0to17,AllPrimaryCarePatientsAge0to17,WellChildVisitsInPastYearAge0to17,AsthmaDiagnosisAge0to17,ed_visit_rate_per_1000,asthma_ed_rate,injury_rate,low_acuity_ratio,primary_care_utilization
4166,420035629001,2017,107,149.0,60.0,60.0,1.0,25.0,75,57,13.0,1392.523364,560.747664,9.345794,0.402685,0.700935
3886,420035512003,2016,102,214.0,40.0,57.0,2.0,41.0,161,106,29.0,2098.039216,558.823529,19.607843,0.186916,1.578431
840,420033001005,2016,115,177.0,84.0,62.0,2.0,29.0,97,61,30.0,1539.130435,539.130435,17.391304,0.474576,0.843478
842,420033001005,2018,115,158.0,62.0,61.0,3.0,30.0,94,61,24.0,1373.913043,530.434783,26.086957,0.392405,0.817391
4026,420035615003,2016,116,114.0,53.0,61.0,1.0,29.0,80,55,20.0,982.758621,525.862069,8.620690,0.464912,0.689655
841,420033001005,2017,115,174.0,64.0,59.0,2.0,32.0,107,73,33.0,1513.043478,513.043478,17.391304,0.367816,0.930435
429,420031803002,2017,109,135.0,34.0,52.0,4.0,19.0,68,46,9.0,1238.532110,477.064220,36.697248,0.251852,0.623853
3888,420035512003,2018,102,204.0,29.0,48.0,2.0,29.0,151,103,26.0,2000.000000,470.588235,19.607843,0.142157,1.480392
50,420031306003,2018,398,613.0,363.0,187.0,5.0,103.0,347,235,58.0,1540.201005,469.849246,12.562814,0.592170,0.871859
3428,420035151002,2018,128,187.0,93.0,59.0,6.0,31.0,137,96,24.0,1460.937500,460.937500,46.875000,0.497326,1.070312

In [ ]:
healthcare_df.sort_values(
    "ed_visit_rate_per_1000",
    ascending=True
).head(10)

,Geo_FIPS,year,pediatric_population,NumberED_VisitsAge0to17,NumberLowAcuityED_VisitsAge0to17,NumberAsthmaRelatedED_Visits,NumberOfInjuryRelatedVisits,NumberAcuteRespiratoryTractInfectionRelatedED_VisitsAge0to17,AllPrimaryCarePatientsAge0to17,WellChildVisitsInPastYearAge0to17,AsthmaDiagnosisAge0to17,ed_visit_rate_per_1000,asthma_ed_rate,injury_rate,low_acuity_ratio,primary_care_utilization
2586,420034741022,2016,425,21.0,9.0,3.0,1.0,3.0,158,151,22.0,49.411765,7.058824,2.352941,0.428571,0.371765
2610,420034742033,2016,737,39.0,9.0,2.0,1.0,6.0,285,251,34.0,52.917232,2.713704,1.356852,0.230769,0.386703
2683,420034753042,2017,584,32.0,8.0,1.0,3.0,2.0,207,183,31.0,54.794521,1.712329,5.136986,0.250000,0.354452
2611,420034742033,2017,737,42.0,11.0,2.0,1.0,3.0,278,251,34.0,56.987788,2.713704,1.356852,0.261905,0.377205
2646,420034752004,2016,479,28.0,12.0,3.0,1.0,4.0,198,170,30.0,58.455115,6.263048,2.087683,0.428571,0.413361
2684,420034753042,2018,584,37.0,13.0,3.0,1.0,6.0,209,175,27.0,63.356164,5.136986,1.712329,0.351351,0.357877
3222,420034961023,2016,378,24.0,7.0,1.0,1.0,5.0,102,77,13.0,63.492063,2.645503,2.645503,0.291667,0.269841
2585,420034741021,2019,591,38.0,18.0,4.0,1.0,5.0,329,289,30.0,64.297800,6.768190,1.692047,0.473684,0.556684
2103,420034560012,2017,941,61.0,19.0,5.0,3.0,8.0,348,286,62.0,64.824655,5.313496,3.188098,0.311475,0.369819
906,420034011002,2018,478,32.0,13.0,6.0,1.0,7.0,222,192,23.0,66.945607,12.552301,2.092050,0.406250,0.464435

In [ ]:
healthcare_df.to_csv(
    "pediatric_population_health_dataset.csv",
    index=False
)

In [ ]:
healthcare_df.to_csv(
    "pediatric_population_health_dataset.csv",
    index=False
)

In [ ]:
healthcare_df["Geo_FIPS"] = healthcare_df["Geo_FIPS"].astype(str)